###
POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "ktkim@elicer.com",
    "password": "1234"
}

###
POST http://localhost:5000/api/product
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTM4MTE3ODR9.zkeo-kAkW8A0qEsV6Xrh86_iL68xr3Y2p4SswWT6H0A 
content-type: application/json

{
    "title": "테스트-제품A",
    "categoryId": "6c91ecdb-7ed7-49ae-af9e-2032df8f7b49",
    "manufacturer": "삼성전자짱",
    "shortDescription": "테스트용 제품입니다.",
    "detailDescription": "테스트용 제품의 자세한 설명입니다.",
    "imageKey": "test-product/test.png",
    "inventory": 100,
    "price": 50000,
    "price": 50000,
    "searchKeywords": [
        "남자", "남자옷"
    ] 
}

###
GET http://localhost:5000/api/productlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTM4MTE3ODR9.zkeo-kAkW8A0qEsV6Xrh86_iL68xr3Y2p4SswWT6H0A 

###
GET http://localhost:5000/api/products/1acafccb-9a6f-44a6-9221-29e1cf81e9c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTM4MTE3ODR9.zkeo-kAkW8A0qEsV6Xrh86_iL68xr3Y2p4SswWT6H0A 

###
PATCH http://localhost:5000/api/products/1acafccb-9a6f-44a6-9221-29e1cf81e9c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTM4MTE3ODR9.zkeo-kAkW8A0qEsV6Xrh86_iL68xr3Y2p4SswWT6H0A 
content-type: application/json

{
    "title": "테스트-제품2",
    "manufacturer": "삼성전자짱2",
    "shortDescription": "테스트용 제품입니다.2",
    "imageKey": "test-product999/test.png",
    "inventory": 50
}

###
DELETE http://localhost:5000/api/products/1acafccb-9a6f-44a6-9221-29e1cf81e9c3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTM4MTE3ODR9.zkeo-kAkW8A0qEsV6Xrh86_iL68xr3Y2p4SswWT6H0A 