###
GET http://localhost:5000/

###
POST http://localhost:5000/api/register
content-type: application/json

{
    "fullName": "kwangtae",
    "email": "ktkim@elicer.com",
    "password": "1234"
}

###
POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "ktkim@elicer.com",
    "password": "1234"
}

###
GET http://localhost:5000/api/userlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjc1YzhiNWZlOGU4ZDI4ODNlMWM5M2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTE4OTg1MzV9.S5zC0LoGD3cBsfkE8YoLTRbpud4hbjmUtkYKNy7TvHA

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjc1YzhiNWZlOGU4ZDI4ODNlMWM5M2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTE5Njg5OTJ9.l4Gm6IBl0UCQneCBo3Jag98qyMgHamMYz3TUVbVqeFg


###
PATCH http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mjc1YzhiNWZlOGU4ZDI4ODNlMWM5M2IiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2NTE5Njg5OTJ9.l4Gm6IBl0UCQneCBo3Jag98qyMgHamMYz3TUVbVqeFg
content-type: application/json

{
    "fullName": "KwangTae",
    "email": "ktkim@elicer.com",
    "currentPassword": "1234"
}


