###
GET http://localhost:5000/

###
POST http://localhost:5000/api/register
content-type: application/json

{
    "fullName": "kwangtae",
    "email": "ktkim444@elicer.com",
    "password": "1234"
}

###
POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "ktkim444@elicer.com",
    "password": "1234"
}

###
GET http://localhost:5000/api/userlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYmFzaWMtdXNlciIsImlhdCI6MTY1MzgwNjE2OX0.QblS3Q-ReI1UyvpbwrbDSlq6BK7-qEdE2gH5r07stqc

###
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYmFzaWMtdXNlciIsImlhdCI6MTY1MzgwNjE2OX0.QblS3Q-ReI1UyvpbwrbDSlq6BK7-qEdE2gH5r07stqc


###
PATCH http://localhost:5000/api/users/826c4d12-8c36-488f-a08d-4c2b51b45081
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4MjZjNGQxMi04YzM2LTQ4OGYtYTA4ZC00YzJiNTFiNDUwODEiLCJyb2xlIjoiYmFzaWMtdXNlciIsImlhdCI6MTY1MzgwNjE2OX0.QblS3Q-ReI1UyvpbwrbDSlq6BK7-qEdE2gH5r07stqc
content-type: application/json

{
    "fullName": "KwangTae2",
    "email": "ktkim@elicer.com",
    "currentPassword": "1234",
    "role": "admin"
}

###
DELETE http://localhost:5000/api/users/5a0a23ad-ddee-41c7-b778-b333a82dbece
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1YTBhMjNhZC1kZGVlLTQxYzctYjc3OC1iMzMzYTgyZGJlY2UiLCJyb2xlIjoiYmFzaWMtdXNlciIsImlhdCI6MTY1Mzc4Njc2NX0.pXReQDiMF-6Y9mwwKH9clFBQMPzPRBxG38D3zojYUzg
